### ISSUE TITLE
nwd-nnw - test divide by 0 and negative numbers

### ISSUE THREAD

**Issue by Maciej3206** [coders-school/cpp-fundamentals#136]
Tests on local machine did not submited an error though the code was not working properly for zero and negative numbers. Tests was stopped but not reported error.

**Comment by ziobron** [comment]
🏅 2 XP granted for @Maciej3206
Thanks for raising this Issue to help to make the course better!

**Comment by Maciej3206** [comment]
Thank You. This is my first issue. Please let me know if I report issue correctly.

**Comment by ziobron** [comment]
I am closing this issue. Tests are proper, on Discord you admitted that it was not passing on local machine either.
