### ISSUE TITLE
typo on the website (sec. 0x02)

### ISSUE THREAD

**Issue by michantoniuk** [coders-school/cpp-fundamentals#272]
You have a small typo (extra 'i') in sec. 0x02 on the website:
https://kursy.coders.school/szkolenie.html?tid=21&lid=268
`make` - komp**l**iluje should be corrected to kompiluje

On the other hand, the corresponding wording in the 02-delivery.md file is fine (no such typo).

**Comment by ziobron** [comment]
🏅 2 XP granted for @michantoniuk
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
Thanks, fixed :)
