### ISSUE TITLE
Issue with points award system

### ISSUE THREAD

**Issue by gyrydymptum** [coders-school/cpp-fundamentals#28]
I got bonus points only for the first task (calculate). For the second task (fibonacci) I saw information about bonus points in github but did not receive it on platform.

**Comment by ziobron** [comment]
🏅 2 XP granted for @gyrydymptum
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
<img width="1217" alt="Zrzut ekranu 2021-05-8 o 08 57 05" src="https://user-images.githubusercontent.com/4595135/117530069-6d37bc80-afdb-11eb-9582-08d2dc23a449.png">

I can see that all points were granted successfully. From my side, it looks ok. Can you confirm that your points are properly calculated or there is still something missing? If everything is ok then please close this Issue :)

**Comment by gyrydymptum** [comment]
Points scored moments after making the issue. 
I thought you could fix it so fast;)
