### ISSUE TITLE
Mistake in description

### ISSUE THREAD

**Issue by michalsoloducha** [coders-school/cpp-fundamentals#477]
In a [lesson](https://kursy.coders.school/szkolenie.html?tid=18&lid=285):
instead of: `int fun(int& ref);    // w argumencie funkcji - przekazanie adresu`
should be: `int fun(int& ref);    // w argumencie funkcji - przekazanie referencji`

**Comment by ziobron** [comment]
🏅 2 XP granted for @michalsoloducha
Thanks for raising this Issue to help to make the course better!
