### ISSUE TITLE
cmake does not run bonus test for password-check

### ISSUE THREAD

**Issue by michantoniuk** [coders-school/cpp-fundamentals#485]
ctest runs only tests from the test.cpp file on the built project

**Comment by ziobron** [comment]
🏅 2 XP granted for @michantoniuk
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
This is done on purpose. I don't want to add the other test case into ctest to allow CI on GitHub work in a proper way.
You can always just run a binary on your own.
Anyway thanks for raising your concerns :)
