### ISSUE TITLE
Double Double points for cooperation in any excersise

### ISSUE THREAD

**Issue by dadus15** [coders-school/cpp-fundamentals#505]
Hi. Me and @WojAbuk try send password-check again because we are done bonus excersise so when we try send password-check again we get points one more time.

**Comment by ziobron** [comment]
🏅 2 XP granted for @dadus15
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
Fixed. From now points for cooperation can only be achieved when points for a task are granted first.
