### ISSUE TITLE
Typo in hazards of (smart) pointers

### ISSUE THREAD

**Issue by LechWilk** [coders-school/cpp-fundamentals#644]
there is:
std::shared_ptr::get()
should be
std::shared_ptr.get()

**Comment by ziobron** [comment]
🏅 2 XP granted for @LechWilk
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
Nope, it's not a typo. To call a function like `.get()` we need an object of `shared_ptr`, eg.
```cpp
std::shared_ptr<int> ptr;
ptr.get();
```
We cannot call `shared_ptr.get()` without an object. And the notation `std::shared_ptr::get()` shows that we mean a get function from the `std::shared_ptr` class.

**Comment by LechWilk** [comment]
ups... 😨
      no issue. Thanx for explanation.
      
      W dniu 2021-06-11 o 12:39, Łukasz Ziobroń pisze:
    
    
      
      Nope, it's not a typo. To call a function like .get()
        we need an object of shared_ptr, eg.
      
        std::shared_ptr<int> ptr;
ptr.get();
      
      We cannot call shared_ptr.get() without an
        object. And the notation std::shared_ptr::get()
        shows that we mean a get function from the std::shared_ptr
        class.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/coders-school/cpp-fundamentals/issues/644#issuecomment-859489049",
"url": "https://github.com/coders-school/cpp-fundamentals/issues/644#issuecomment-859489049",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
