### ISSUE TITLE
NWW test seems to be crashing

### ISSUE THREAD

**Issue by michantoniuk** [coders-school/cpp-fundamentals#66]
It looks like the CMake tests simply stop running mid NWW testing (every time on run NWWFixtureTest/NWWFixture.ShouldCalculateNWW/6) even the all the previous tests show OK.

Log attached.

[NWW_tests_log.txt](https://github.com/coders-school/cpp-fundamentals/files/6446137/NWW_tests_log.txt)

**Comment by ziobron** [comment]
🏅 2 XP granted for @michantoniuk
Thanks for raising this Issue to help to make the course better!

**Comment by michantoniuk** [comment]
Turns out it was caused by my forgetting to secure the code against division by 0. :)
